# Generated by cask-dotfile-generator
# Created by: @seethroughtrees
# https://github.com/seethroughtrees/brew-cask-dotfile-generator


install ack
install autojump
install ccat
install ctags
install ffmpeg
install fzf
install gcc
install git
install go
install hugo
install imagemagick
install mas
install neovim
install node
install peco
install python3
install rbenv
install speedtest-cli
install the-platinum-searcher
install thefuck
install tldr
install tmux
install vimpager
install yarn
install youtube-dl
install zsh
